import type { Metadata } from "next";
import { Archivo , Poppins, Bebas_Neue, Bungee} from "next/font/google";
import "./globals.css";
// Khai báo font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // chọn trọng lượng cần dùng
  variable: "--font-poppins",    // gắn vào biến CSS
});

// const bungee_init = Bungee({
//   subsets: ['latin'],
//   weight: ['400'],
//   variable: '--heading',
// });
const archivo_init = Archivo({
  subsets: ['latin'],
  weight: ['900'],
  variable: '--heading',
});

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas",
});


export const metadata: Metadata = {
  icons: {
    icon: "/ava.png",
  },
  title: "Judo Quân Khu 7",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body
        className={`${poppins.variable} ${bebas.variable} ${archivo_init.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
