import type { Metadata } from "next";
import { Archivo, Poppins, Bebas_Neue, Outfit } from "next/font/google";
import "../globals.css";
import { Analytics } from '@vercel/analytics/next';
import Preloader from "../../component/preloader/Preloader";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
// Khai báo font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // chọn trọng lượng cần dùng
  variable: "--font-poppins",    // gắn vào biến CSS
});

// const bungee_init = Bungee({
//   subsets: ['latin'],
//   weight: ['400'],
//   variable: '--heading',
// });
const archivo_init = Archivo({
  subsets: ['latin'],
  weight: ['900'],
  variable: '--heading',
});

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas",
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  icons: {
    icon: "/ava.png",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
  title: "Judo Quân Khu 7",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: string } | Promise<{ locale: string }>;
}) {
  const resolvedParams = await params;
  const messages = await getMessages();

  return (
    <html lang={resolvedParams.locale}>
      <body
        className={`${poppins.variable} ${bebas.variable} ${archivo_init.variable} ${outfit.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <Preloader />
          {children}
          <Analytics />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
